package io.radanalytics.eventstreamdecisions;

import io.radanalytics.eventstreamdecisions.Event;

rule "CC Transaction Approved"
  when
    e: Event(eventCategory == "CC_TRANSACTION", confidence >= 25)
  then
    e.setNextEvent("CC_PAYMENT_APPROVED");
end

rule "CC Transaction Declined"
  when
    e: Event(eventCategory == "CC_TRANSACTION", confidence < 25)
  then
    e.setNextEvent("CC_PAYMENT_DECLINED");
end

rule "Late Payment Waiver Offer"
  when
    e: Event(eventCategory == "CC_BALANCE_PAYMENT", eventValue == "LATE_PAYMENT", confidence >= 75)
  then
    e.setNextEvent("LATE_PAYMENT_WAIVER");
end

rule "Late Payment"
  when
    e: Event(eventCategory == "CC_BALANCE_PAYMENT", eventValue == "LATE_PAYMENT", confidence < 75)
  then
    e.setNextEvent("LATE_PAYMENT_NO_WAIVER");
end

rule "Balance Payment"
  when
    e: Event(eventCategory == "CC_BALANCE_PAYMENT", eventValue == "MIN_DUE")
  then
    e.setNextEvent("CC_PAYMENT_RECEIVED");
end

rule "Dispute Created"
  when
    e: Event(eventCategory == "DISPUTES", eventValue == "CASE_CREATED")
  then
    e.setNextEvent("DISPUTE_CASE_CREATED");
end

rule "Dispute Closed"
  when
    e: Event(eventCategory == "DISPUTES", eventValue == "CASE_CLOSED")
  then
    e.setNextEvent("DISPUTE_CASE_CLOSED");
end

rule "Online Payment Failed"
  when
    e: Event(eventCategory == "ONLINE_ACCOUNT", eventValue == "PAYMENT_FAILURE")
  then
    e.setNextEvent("ONLINE_PAYMENT_FAILURE");
end

rule "Online Payment Success"
  when
    e: Event(eventCategory == "ONLINE_ACCOUNT", eventValue == "PAYMENT_SUCCESS")
  then
    e.setNextEvent("ONLINE_PAYMENT_SUCCESS");
end
